version: '3'

services:
  app:
    build: 
        context: ./
        dockerfile: src/Dockerfile
    ports:
        - "19202:3000"
    volumes:
        - .:/src
    depends_on:
        - db
  db:
    build:
        context: ./
        dockerfile: mysql/Dockerfile
    environment: 
        MYSQL_DATABASE: blog_db
        MYSQL_USER: javier
        MYSQL_PASSWORD: psswrd
        MYSQL_ROOT_PASSWORD: secret
    ports:
        - "3007:3306"
    volumes:
        - ./mysql-data:/var/lib/mysql
